/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightapp;

import java.awt.dnd.DropTarget;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author csz5024
 */
public class FlightAppJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FlightAppJFrame
     */
    public FlightAppJFrame() {
        initComponents();
        
        //DBConnectionOld.retrieveFlightNames();
        //DBConnectionOld.retrieveDates();
        
        //adds customer names to various JComboBoxes
        for(String i: Customer.getCustomer()) {
            BookNameJCombo.addItem(i);
            CancelNameJCombo.addItem(i);
            StatusJCombo.addItem(i);
        }
        
        for(String d: Day.getDay()) {
            BookDateJCombo.addItem(d);
            CancelDateJCombo.addItem(d);
            StatusDateJCombo.addItem(d);
            WaitlistDateJCombo.addItem(d);            
        }
        
        for(String f: Flight.getFLIGHTnames()) {
            BookFlightNumJCombo.addItem(f);
            StatusFlightNumJCombo.addItem(f);
            DropFlightJCombo.addItem(f);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AddCustomer = new javax.swing.JPanel();
        AddNameTextField = new javax.swing.JTextField();
        AddNameLabel = new javax.swing.JLabel();
        AddNameSubmit = new javax.swing.JButton();
        AddNamePrompt = new javax.swing.JLabel();
        AddDate = new javax.swing.JPanel();
        AddDateSpinner = new javax.swing.JSpinner();
        AddDateSubmit = new javax.swing.JButton();
        AddDateLabel = new javax.swing.JLabel();
        AddDatePrompt = new javax.swing.JLabel();
        AddFlight = new javax.swing.JPanel();
        AddFlightNameL = new javax.swing.JLabel();
        AddFlightSeatL = new javax.swing.JLabel();
        AFNameTF = new javax.swing.JTextField();
        AddFlightSubmit = new javax.swing.JButton();
        AddFlightPrompt = new javax.swing.JLabel();
        AFSeatNum = new javax.swing.JSpinner();
        DropFlight = new javax.swing.JPanel();
        DropFlightLabel = new javax.swing.JLabel();
        DropFlightJCombo = new javax.swing.JComboBox<>();
        DropFlightSubmit = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        DropFlightTextArea = new javax.swing.JTextArea();
        BookFlight = new javax.swing.JPanel();
        BookNameLabel = new javax.swing.JLabel();
        BookDateLabel = new javax.swing.JLabel();
        BookFlightNumLabel = new javax.swing.JLabel();
        BookDateJCombo = new javax.swing.JComboBox<>();
        BookNameJCombo = new javax.swing.JComboBox<>();
        BookFlightNumJCombo = new javax.swing.JComboBox<>();
        BookSubmit = new javax.swing.JButton();
        BookOutputContainer = new javax.swing.JPanel();
        BookFlightNumOutputLabel = new javax.swing.JLabel();
        BookDateOutputLabel = new javax.swing.JLabel();
        BookFlightNumOutput = new javax.swing.JLabel();
        BookDateOutput = new javax.swing.JLabel();
        BookCustomerOutputLabel = new javax.swing.JLabel();
        BookCustomerOutput = new javax.swing.JLabel();

        BookPrompt = new javax.swing.JLabel();

        CancelFlight = new javax.swing.JPanel();
        CancelDateLabel = new javax.swing.JLabel();
        CancelNameLabel = new javax.swing.JLabel();
        CancelSubmit = new javax.swing.JButton();
        CancelNameJCombo = new javax.swing.JComboBox<>();
        CancelDateJCombo = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        CancelTextArea = new javax.swing.JTextArea();
        Status = new javax.swing.JPanel();
        StatusLabel = new javax.swing.JLabel();
        StatusJCombo = new javax.swing.JComboBox<>();
        StatusSubmit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        StatusTextArea = new javax.swing.JTextArea();
        FlightStatus = new javax.swing.JPanel();
        StatusDateLabel = new javax.swing.JLabel();
        StatusFlightNumLabel = new javax.swing.JLabel();
        StatusDateJCombo = new javax.swing.JComboBox<>();
        StatusFlightNumJCombo = new javax.swing.JComboBox<>();
        FStatusSubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FStatusTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Waitlist = new javax.swing.JPanel();
        WaitlistDateLabel = new javax.swing.JLabel();
        WaitlistDateJCombo = new javax.swing.JComboBox<>();
        WaitlistSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        WaitlistTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fly-By-Night Flight Scheduler");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fly-By-Night");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Flight Scheduler");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTabbedPane1.setName("Booking"); // NOI18N

        AddNameTextField.setColumns(20);

        AddNameLabel.setText("Enter your first name:");

        AddNameSubmit.setText("Submit");
        AddNameSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNameSubmitActionPerformed(evt);
            }
        });

        AddNamePrompt.setVisible(false);
        AddNamePrompt.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        AddNamePrompt.setText("null");

        javax.swing.GroupLayout AddCustomerLayout = new javax.swing.GroupLayout(AddCustomer);
        AddCustomer.setLayout(AddCustomerLayout);
        AddCustomerLayout.setHorizontalGroup(
            AddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddNameLabel)
                    .addComponent(AddNameSubmit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(AddCustomerLayout.createSequentialGroup()
                        .addComponent(AddNamePrompt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddCustomerLayout.setVerticalGroup(
            AddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addGroup(AddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNameSubmit)
                    .addComponent(AddNamePrompt))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Add Customer", AddCustomer);

        AddDateSpinner.setModel(new javax.swing.SpinnerDateModel());

        AddDateSubmit.setText("Submit");
        AddDateSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateSubmitActionPerformed(evt);
            }
        });

        AddDateLabel.setText("Select a date to add:");

        AddDatePrompt.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        AddDatePrompt.setText("null");
        AddDatePrompt.setVisible(false);

        javax.swing.GroupLayout AddDateLayout = new javax.swing.GroupLayout(AddDate);
        AddDate.setLayout(AddDateLayout);
        AddDateLayout.setHorizontalGroup(
            AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDateLayout.createSequentialGroup()
                .addGroup(AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddDateLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(AddDateSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddDatePrompt))
                    .addGroup(AddDateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(499, Short.MAX_VALUE))
        );
        AddDateLayout.setVerticalGroup(
            AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addGroup(AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDateSubmit)
                    .addComponent(AddDatePrompt))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Add Date", AddDate);

        AddFlightNameL.setText("Enter a flight name:");

        AddFlightSeatL.setText("Enter a number of seats:");

        AFNameTF.setColumns(25);

        AddFlightSubmit.setText("Submit");
        AddFlightSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightSubmitActionPerformed(evt);
            }
        });

        AddFlightPrompt.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        AddFlightPrompt.setText("null");
        AddFlightPrompt.setVisible(false);

        AFSeatNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout AddFlightLayout = new javax.swing.GroupLayout(AddFlight);
        AddFlight.setLayout(AddFlightLayout);
        AddFlightLayout.setHorizontalGroup(
            AddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddFlightSubmit)
                    .addGroup(AddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AddFlightSeatL)
                        .addComponent(AddFlightNameL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(AddFlightLayout.createSequentialGroup()
                        .addGroup(AddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddFlightPrompt)
                            .addComponent(AFSeatNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddFlightLayout.setVerticalGroup(
            AddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFlightNameL)
                    .addComponent(AFNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFlightSeatL)
                    .addComponent(AFSeatNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addGroup(AddFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFlightSubmit)
                    .addComponent(AddFlightPrompt))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Add Flight", AddFlight);

        DropFlightLabel.setText("Select Flight to Drop:");

        DropFlightJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flight" }));

        DropFlightSubmit.setText("Submit");
        DropFlightSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropFlightSubmitActionPerformed(evt);
            }
        });

        DropFlightTextArea.setColumns(20);
        DropFlightTextArea.setRows(5);
        jScrollPane4.setViewportView(DropFlightTextArea);

        javax.swing.GroupLayout DropFlightLayout = new javax.swing.GroupLayout(DropFlight);
        DropFlight.setLayout(DropFlightLayout);
        DropFlightLayout.setHorizontalGroup(
            DropFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DropFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DropFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DropFlightSubmit)
                    .addComponent(DropFlightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DropFlightJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        DropFlightLayout.setVerticalGroup(
            DropFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DropFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DropFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DropFlightLayout.createSequentialGroup()
                        .addGroup(DropFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DropFlightLabel)
                            .addComponent(DropFlightJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DropFlightSubmit)
                        .addGap(40, 40, 40))
                    .addGroup(DropFlightLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Drop Flight", DropFlight);

        BookNameLabel.setText("Select Your Name:");

        BookDateLabel.setText("Select Departure Date:");

        BookFlightNumLabel.setText("Select Flight Number:");

        BookDateJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date" }));

        BookNameJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name" }));
        BookNameJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookNameJComboActionPerformed(evt);
            }
        });

        BookFlightNumJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flight" }));

        BookSubmit.setText("Submit");
        BookSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookSubmitActionPerformed(evt);
            }
        });

        BookOutputContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        BookFlightNumOutputLabel.setText("Flight Number:");

        BookDateOutputLabel.setText("Date:");

        BookFlightNumOutput.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BookFlightNumOutput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookFlightNumOutput.setText("null");
        BookFlightNumOutput.setVisible(false);

        BookDateOutput.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BookDateOutput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookDateOutput.setText("null");
        BookDateOutput.setVisible(false);

        BookCustomerOutputLabel.setText("Customer:");

        BookCustomerOutput.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BookCustomerOutput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookCustomerOutput.setText("null");
        BookCustomerOutput.setVisible(false);

        BookPrompt.setText("Flight Full! Added to Waitlist");
        BookPrompt.setVisible(false);

        javax.swing.GroupLayout BookOutputContainerLayout = new javax.swing.GroupLayout(BookOutputContainer);
        BookOutputContainer.setLayout(BookOutputContainerLayout);
        BookOutputContainerLayout.setHorizontalGroup(
            BookOutputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookOutputContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookOutputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookOutputContainerLayout.createSequentialGroup()
                        .addComponent(BookPrompt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BookOutputContainerLayout.createSequentialGroup()
                        .addGroup(BookOutputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookDateOutputLabel)
                            .addComponent(BookFlightNumOutputLabel)
                            .addComponent(BookCustomerOutputLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BookOutputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookOutputContainerLayout.createSequentialGroup()
                                .addComponent(BookFlightNumOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42))
                            .addGroup(BookOutputContainerLayout.createSequentialGroup()
                                .addGroup(BookOutputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BookDateOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(BookCustomerOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(331, 331, 331))
        );
        BookOutputContainerLayout.setVerticalGroup(
            BookOutputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookOutputContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookOutputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookCustomerOutputLabel)
                    .addComponent(BookCustomerOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookOutputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookDateOutputLabel)
                    .addComponent(BookDateOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookOutputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookFlightNumOutputLabel)
                    .addComponent(BookFlightNumOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BookPrompt)
                .addContainerGap())
        );

        javax.swing.GroupLayout BookFlightLayout = new javax.swing.GroupLayout(BookFlight);
        BookFlight.setLayout(BookFlightLayout);
        BookFlightLayout.setHorizontalGroup(
            BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BookFlightLayout.createSequentialGroup()
                        .addGroup(BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BookSubmit)
                            .addGroup(BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BookDateLabel)
                                .addComponent(BookNameLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BookNameJCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BookDateJCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookFlightLayout.createSequentialGroup()
                        .addComponent(BookFlightNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookFlightNumJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookOutputContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BookFlightLayout.setVerticalGroup(
            BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookFlightLayout.createSequentialGroup()
                        .addComponent(BookOutputContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(BookFlightLayout.createSequentialGroup()
                        .addGroup(BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookNameLabel)
                            .addComponent(BookNameJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookDateLabel)
                            .addComponent(BookDateJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookFlightNumLabel)
                            .addComponent(BookFlightNumJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(BookSubmit)
                        .addGap(40, 40, 40))))
        );

        jTabbedPane1.addTab("Book Flight", BookFlight);

        CancelDateLabel.setText("Select Departure Date:");

        CancelNameLabel.setText("Select Your Name:");

        CancelSubmit.setText("Submit");
        CancelSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelSubmitActionPerformed(evt);
            }
        });

        CancelNameJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name" }));

        CancelDateJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date" }));

        CancelTextArea.setColumns(20);
        CancelTextArea.setRows(5);
        jScrollPane5.setViewportView(CancelTextArea);

        javax.swing.GroupLayout CancelFlightLayout = new javax.swing.GroupLayout(CancelFlight);
        CancelFlight.setLayout(CancelFlightLayout);
        CancelFlightLayout.setHorizontalGroup(
            CancelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CancelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CancelSubmit)
                    .addGroup(CancelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CancelDateLabel)
                        .addComponent(CancelNameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CancelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CancelNameJCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelDateJCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        CancelFlightLayout.setVerticalGroup(
            CancelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CancelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancelFlightLayout.createSequentialGroup()
                        .addGroup(CancelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelNameLabel)
                            .addComponent(CancelNameJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CancelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelDateLabel)
                            .addComponent(CancelDateJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addComponent(CancelSubmit)
                        .addGap(40, 40, 40))
                    .addGroup(CancelFlightLayout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Cancel Booking", CancelFlight);

        StatusLabel.setText("Select customer name:");

        StatusJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name" }));

        StatusSubmit.setText("Submit");
        StatusSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusSubmitActionPerformed(evt);
            }
        });

        StatusTextArea.setColumns(20);
        StatusTextArea.setRows(5);
        jScrollPane3.setViewportView(StatusTextArea);

        javax.swing.GroupLayout StatusLayout = new javax.swing.GroupLayout(Status);
        Status.setLayout(StatusLayout);
        StatusLayout.setHorizontalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StatusSubmit)
                    .addComponent(StatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StatusJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        StatusLayout.setVerticalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusLayout.createSequentialGroup()
                        .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusLabel)
                            .addComponent(StatusJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StatusSubmit)
                        .addGap(40, 40, 40))
                    .addGroup(StatusLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Status", Status);

        StatusDateLabel.setText("Select Departure Date:");

        StatusFlightNumLabel.setText("Select Flight Number:");

        StatusDateJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date" }));

        StatusFlightNumJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flight" }));

        FStatusSubmit.setText("Submit");
        FStatusSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FStatusSubmitActionPerformed(evt);
            }
        });

        FStatusTextArea.setColumns(20);
        FStatusTextArea.setRows(5);
        jScrollPane2.setViewportView(FStatusTextArea);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Obsolete from part 1, but still functional");

        javax.swing.GroupLayout FlightStatusLayout = new javax.swing.GroupLayout(FlightStatus);
        FlightStatus.setLayout(FlightStatusLayout);
        FlightStatusLayout.setHorizontalGroup(
            FlightStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FlightStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(FlightStatusLayout.createSequentialGroup()
                        .addGroup(FlightStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FlightStatusLayout.createSequentialGroup()
                                .addGroup(FlightStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FStatusSubmit)
                                    .addComponent(StatusDateLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StatusDateJCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FlightStatusLayout.createSequentialGroup()
                                .addComponent(StatusFlightNumLabel)
                                .addGap(18, 18, 18)
                                .addComponent(StatusFlightNumJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FlightStatusLayout.setVerticalGroup(
            FlightStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FlightStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FlightStatusLayout.createSequentialGroup()
                        .addGroup(FlightStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusDateLabel)
                            .addComponent(StatusDateJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FlightStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusFlightNumLabel)
                            .addComponent(StatusFlightNumJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FStatusSubmit))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Flight Status", FlightStatus);

        WaitlistDateLabel.setText("Select Departure Date:");

        WaitlistDateJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date" }));

        WaitlistSubmit.setText("Submit");
        WaitlistSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitlistSubmitActionPerformed(evt);
            }
        });

        WaitlistTextArea.setColumns(20);
        WaitlistTextArea.setRows(5);
        jScrollPane1.setViewportView(WaitlistTextArea);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Obsolete from Part 1, but still functional");

        javax.swing.GroupLayout WaitlistLayout = new javax.swing.GroupLayout(Waitlist);
        Waitlist.setLayout(WaitlistLayout);
        WaitlistLayout.setHorizontalGroup(
            WaitlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitlistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WaitlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WaitlistLayout.createSequentialGroup()
                        .addGroup(WaitlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(WaitlistSubmit)
                            .addComponent(WaitlistDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WaitlistDateJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(WaitlistLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        WaitlistLayout.setVerticalGroup(
            WaitlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitlistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WaitlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(WaitlistLayout.createSequentialGroup()
                        .addGroup(WaitlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaitlistDateLabel)
                            .addComponent(WaitlistDateJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(WaitlistSubmit))
                    .addGroup(WaitlistLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Waitlist", Waitlist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Booking");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //obsolete from part 1, still funcitonal
    private void WaitlistSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitlistSubmitActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == WaitlistSubmit) {
            String selectDDate = WaitlistDateJCombo.getSelectedItem().toString();
            
            String customer = BookingQueries.checkWaitlist(selectDDate);
            WaitlistTextArea.setText(customer);
            
            
            
        }
    }//GEN-LAST:event_WaitlistSubmitActionPerformed

    private void AddNameSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNameSubmitActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == AddNameSubmit) {
            
            final String name = AddNameTextField.getText();
            boolean isDupe = Customer.addCustomer(name);
            
            //checks for duplicate names in the database
            if (isDupe) {
                ArrayList<String> customers = Customer.getCustomer();
                
                BookNameJCombo.removeAllItems();
                CancelNameJCombo.removeAllItems();
                StatusJCombo.removeAllItems();
                for (String i : customers) {
                    BookNameJCombo.addItem(i);
                    CancelNameJCombo.addItem(i);
                    StatusJCombo.addItem(i);
                }
                AddNamePrompt.setText(name + " added successfully!");
                
            }
            else {
                AddNamePrompt.setText(name + " is already in use! please choose another");
            }
            
            AddNamePrompt.setVisible(true);
            
        }
        
    }//GEN-LAST:event_AddNameSubmitActionPerformed

    private void BookSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookSubmitActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == BookSubmit) {
            
            //retrieve selections from JCombo boxes
            String selectedBDate = BookDateJCombo.getSelectedItem().toString();
            BookDateOutput.setText(selectedBDate);
            String selectedBFlight = BookFlightNumJCombo.getSelectedItem().toString();
            BookFlightNumOutput.setText(selectedBFlight);
            String selectedBName = BookNameJCombo.getSelectedItem().toString();
            BookCustomerOutput.setText(selectedBName);
            Timestamp timestamp = new Timestamp(Calendar.getInstance().getTime().getTime());
            
            //set JCombo selections in BookingEntry class
            BookingEntry book = new BookingEntry(selectedBName, selectedBFlight, selectedBDate, timestamp);
            boolean isFull = BookingQueries.flightFull(selectedBFlight, selectedBDate);
            
            if (isFull) {
                BookPrompt.setText("Flight full, added to Waitlist");
            }
            else {
                BookPrompt.setText("Flight Booked!");
            }
            
            boolean bookingsAdd = BookingQueries.addBooking(book, isFull);
            if (!bookingsAdd){
                BookPrompt.setText("Flight already Booked!");
            }
            BookPrompt.setVisible(true);
            BookDateOutput.setVisible(true);
            BookFlightNumOutput.setVisible(true);
            BookCustomerOutput.setVisible(true);
        }
    }//GEN-LAST:event_BookSubmitActionPerformed

    private void CancelSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelSubmitActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == CancelSubmit) {
            String selectedName = CancelNameJCombo.getSelectedItem().toString();
            String selectedDate = CancelDateJCombo.getSelectedItem().toString();
            String feedback;

            feedback = BookingQueries.cancelBooking(selectedName, selectedDate);
            feedback += BookingQueries.cancelWaitlist(selectedName, selectedDate);
            feedback += BookingQueries.waitToBooking();
            
            CancelTextArea.setText(feedback);
        }
    }//GEN-LAST:event_CancelSubmitActionPerformed

    //obsolete from part 1, still funcitonal
    private void FStatusSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FStatusSubmitActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == FStatusSubmit) {
            
            final String selectedDate = StatusDateJCombo.getSelectedItem().toString();
            final String selectedFlight = StatusFlightNumJCombo.getSelectedItem().toString();
            //int selectedFlightIndex;
            //String selectedSeatNum;
            //ArrayList<String> flights = Flight.getFLIGHTnames();
            //ArrayList<String> seats = Flight.getFLIGHTseats();
            
            //gets the total number of seats for the selected flight
            //selectedFlightIndex = flights.indexOf(selectedFlight);
            //selectedSeatNum = (String) seats.get(selectedFlightIndex);
            
            //subtract number of people booked from total here
            //BookingQueries.flightFull(selectedFlight, selectedDate);
            //int availableSeats = Integer.parseInt(selectedSeatNum) - Flight.getSeatSub();
            //int numSeats = BookingQueries.checkWaitlistNum(selectedDate, selectedFlight);
            
            //System.out.println(selectedSeatNum + Flight.getSeatSub() + "\n");
   
            String booking = BookingQueries.checkBookings(selectedFlight, selectedDate);
            FStatusTextArea.setText(booking);
                
        }
    }//GEN-LAST:event_FStatusSubmitActionPerformed

    //dont know how to get rid of this
    private void BookNameJComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNameJComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookNameJComboActionPerformed

    private void AddDateSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateSubmitActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == AddDateSubmit) {
            
            SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
            String spinnerValue = formater.format(AddDateSpinner.getValue());
            Date day = Date.valueOf(spinnerValue);
            
            //for some reason it wont let me compile Day.addDate(day) without adding a redundant try catch block
            try {
                if (Day.addDate(day) == true) {
                    AddDatePrompt.setText(day+" added successfully!");
                    
                    BookDateJCombo.removeAllItems();
                    CancelDateJCombo.removeAllItems();
                    StatusDateJCombo.removeAllItems();
                    WaitlistDateJCombo.removeAllItems();
                    for(String d: Day.getDay()) {
                        BookDateJCombo.addItem(d);
                        CancelDateJCombo.addItem(d);
                        StatusDateJCombo.addItem(d);
                        WaitlistDateJCombo.addItem(d);            
                    }  
                }
                else {
                    AddDatePrompt.setText(day+" already added, please select another date");
                }
                AddDatePrompt.setVisible(true);
                    
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_AddDateSubmitActionPerformed

    private void AddFlightSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightSubmitActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == AddFlightSubmit) {
            
            String flightName = AFNameTF.getText();
            int numSeats = (int)AFSeatNum.getValue();
            
            if (Flight.addFlight(flightName, numSeats) == true) {
                AddFlightPrompt.setText(flightName+" added successfully!");
                
                BookFlightNumJCombo.removeAllItems();
                StatusFlightNumJCombo.removeAllItems();
                DropFlightJCombo.removeAllItems();
                for(String f: Flight.getFLIGHTnames()) {
                    BookFlightNumJCombo.addItem(f);
                    StatusFlightNumJCombo.addItem(f);
                    DropFlightJCombo.addItem(f);
                }
            }
            else {
                AddFlightPrompt.setText("flight name already in use, please choose another");
            }
            AddFlightPrompt.setVisible(true);
        }
    }//GEN-LAST:event_AddFlightSubmitActionPerformed

    private void StatusSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusSubmitActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == StatusSubmit) {
            
            final String customer = StatusJCombo.getSelectedItem().toString();
            
            String status = BookingQueries.Status(customer);
            StatusTextArea.setText(status);
        }
    }//GEN-LAST:event_StatusSubmitActionPerformed

    private void DropFlightSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropFlightSubmitActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == DropFlightSubmit) {
            
            final String flight = DropFlightJCombo.getSelectedItem().toString();
            
            
            String status = BookingQueries.dropFlight(flight);
            DropFlightTextArea.setText(status);
        }
    }//GEN-LAST:event_DropFlightSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightAppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightAppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightAppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightAppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightAppJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AFNameTF;
    private javax.swing.JSpinner AFSeatNum;
    private javax.swing.JPanel AddCustomer;
    private javax.swing.JPanel AddDate;
    private javax.swing.JLabel AddDateLabel;
    private javax.swing.JLabel AddDatePrompt;
    private javax.swing.JSpinner AddDateSpinner;
    private javax.swing.JButton AddDateSubmit;
    private javax.swing.JPanel AddFlight;
    private javax.swing.JLabel AddFlightNameL;
    private javax.swing.JLabel AddFlightPrompt;
    private javax.swing.JLabel AddFlightSeatL;
    private javax.swing.JButton AddFlightSubmit;
    private javax.swing.JLabel AddNameLabel;
    private javax.swing.JLabel AddNamePrompt;
    private javax.swing.JButton AddNameSubmit;
    private javax.swing.JTextField AddNameTextField;
    private javax.swing.JLabel BookCustomerOutput;
    private javax.swing.JLabel BookCustomerOutputLabel;
    private javax.swing.JComboBox<String> BookDateJCombo;
    private javax.swing.JLabel BookDateLabel;
    private javax.swing.JLabel BookDateOutput;
    private javax.swing.JLabel BookDateOutputLabel;
    private javax.swing.JPanel BookFlight;
    private javax.swing.JComboBox<String> BookFlightNumJCombo;
    private javax.swing.JLabel BookFlightNumLabel;
    private javax.swing.JLabel BookFlightNumOutput;
    private javax.swing.JLabel BookFlightNumOutputLabel;
    private javax.swing.JComboBox<String> BookNameJCombo;
    private javax.swing.JLabel BookNameLabel;
    private javax.swing.JPanel BookOutputContainer;
    private javax.swing.JLabel BookPrompt;
    private javax.swing.JButton BookSubmit;
    private javax.swing.JComboBox<String> CancelDateJCombo;
    private javax.swing.JLabel CancelDateLabel;
    private javax.swing.JPanel CancelFlight;
    private javax.swing.JComboBox<String> CancelNameJCombo;
    private javax.swing.JLabel CancelNameLabel;
    private javax.swing.JButton CancelSubmit;
    private javax.swing.JTextArea CancelTextArea;
    private javax.swing.JPanel DropFlight;
    private javax.swing.JComboBox<String> DropFlightJCombo;
    private javax.swing.JLabel DropFlightLabel;
    private javax.swing.JButton DropFlightSubmit;
    private javax.swing.JTextArea DropFlightTextArea;
    private javax.swing.JButton FStatusSubmit;
    private javax.swing.JTextArea FStatusTextArea;
    private javax.swing.JPanel FlightStatus;
    private javax.swing.JPanel Status;
    private javax.swing.JComboBox<String> StatusDateJCombo;
    private javax.swing.JLabel StatusDateLabel;
    private javax.swing.JComboBox<String> StatusFlightNumJCombo;
    private javax.swing.JLabel StatusFlightNumLabel;
    private javax.swing.JComboBox<String> StatusJCombo;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JButton StatusSubmit;
    private javax.swing.JTextArea StatusTextArea;
    private javax.swing.JPanel Waitlist;
    private javax.swing.JComboBox<String> WaitlistDateJCombo;
    private javax.swing.JLabel WaitlistDateLabel;
    private javax.swing.JButton WaitlistSubmit;
    private javax.swing.JTextArea WaitlistTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
